name: Code Workflow

on: [push, pull_request]

jobs:
  compile:
    name: Compile Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile code
        run: |
          make re

  issue_on_failure:
    name: Issue on Workflow Failure
    runs-on: ubuntu-latest
    
    if: failure()

    steps:
      - name: Create issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = 'Workflow Failure';
            const issueBody = `The code workflow has failed. Please investigate and resolve the issue.`;
            const createIssue = async () => {
              const { data: newIssue } = await github.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: issueBody
              });
              console.log(`Created issue ${newIssue.number}`);
            };
            createIssue();